export const EXPLORE_PROVIDER_COPY = {
  title: "Place search provider",
  description: "Choose the primary service for places and photos on web and mobile. Google can switch to a fallback when its configured free allowance is reached.",
  label: "Provider",
  loading: "Loading provider settings…",
  saving: "Saving…",
  save: "Save provider",
  credentials: "Services without a configured server API key are unavailable. A configured key still requires an active account, sufficient credits, and the appropriate API enabled.",
  configured: "Key configured",
  missing: "Key missing",
  error: "Provider settings could not be loaded or saved. Please try again.",
  retry: "Reload settings",
  saved: "Provider saved. New searches will use this selection.",
  google: "Google Places",
  serper: "Serper",
  serpent: "Serpent API",
  serpent_options: "Serpent options",
  serpent_maps_quick: "Enable photos",
  serpent_maps_quick_description: "Maps Quick loads photos and richer details for the list with an additional paid request. Serpent Image Search loads matching photos only as places become visible, with cached lookups; it does not add richer Maps details. Uncertain matches keep a placeholder. Disabling photos uses Maps List alone. Applies on web and mobile, including Google's Serpent fallback. Optional web search is charged separately.",
  photo_source: "Photo source",
  photo_maps_quick: "Maps Quick",
  photo_image_search: "Serpent Image Search",
  openstreetmap: "OpenStreetMap",
  fallback_enabled: "Switch provider after Google's free allowance",
  fallback_label: "Fallback provider",
  fallback_description: "Used when either Google allowance cannot cover the next search, or Google returns a quota error. Google resumes automatically next billing month. Other errors remain visible; there is no chain of paid fallbacks.",
  search_limit: "Monthly Google search allowance",
  photo_limit: "Monthly Google photo allowance",
  search_offset: "Earlier or external Google searches this month",
  photo_offset: "Earlier or external Google photo requests this month",
  budget_note: "Check your billing account's actual free limits. Global Enterprise search and photo limits are 1,000 each; eligible India accounts get 7,000 each. Earlier or external usage is shared across projects and must be entered here. Estimates can be increased, but not lowered during the month.",
  usage: "This month's tracked requests",
  usage_counts: "Searches: {searches} · Photos: {photos} · Billing month: {month}",
  reservation_note: "Up to 20 photo requests are reserved before a Google search; unused slots are returned. Switching may happen slightly before the photo limit. Failed or uncertain requests are counted conservatively. This guard covers Explore requests, not untracked calls from other apps.",
} as const;
