export const STORAGE_COPY = {
  nav: { translationKey: "admin.storage.nav", defaultText: "Chat storage" },
  title: { translationKey: "admin.storage.title", defaultText: "Chat file storage" },
  policy: { translationKey: "admin.storage.policy", defaultText: "No storage quota is imposed. Daily cleanup removes unused uploads after at least 24 hours and files used only by deleted chats after at least 7 days. Existing chats, configured character images and prompt icons retain their files." },
  restore: { translationKey: "admin.storage.restore", defaultText: "Files used only by deleted chats may be removed after 7 days. Chats with expired attachments cannot be restored; restore them within the grace period if needed." },
  alert: { translationKey: "admin.storage.alert", defaultText: "Accounts using at least {limit}: {count}. This is a review alert, not a usage restriction." },
  failed: { translationKey: "admin.storage.failed", defaultText: "{count} file deletions need review or retry. Their storage is still counted." },
  runFailed: { translationKey: "admin.storage.run_failed", defaultText: "The last maintenance run did not finish successfully. Review its result before relying on cleanup." },
  unavailable: { translationKey: "admin.storage.unavailable", defaultText: "Storage information is unavailable. Other admin sections remain available. Refresh to try again." },
  total: { translationKey: "admin.storage.total", defaultText: "Tracked storage: {bytes} across {files} files." },
  inventory: { translationKey: "admin.storage.inventory", defaultText: "The initial storage inventory is not complete yet. Usage figures cover confirmed files only." },
  unknown: { translationKey: "admin.storage.unknown", defaultText: "Files awaiting inventory confirmation: {count}." },
  lastRun: { translationKey: "admin.storage.last_run", defaultText: "Last maintenance run: {date}" },
  notRun: { translationKey: "admin.storage.not_run", defaultText: "Not run yet" },
  runResult: { translationKey: "admin.storage.run_result", defaultText: "Last run: {deleted} files removed, {failed} failed, {deferred} deferred." },
  dryRun: { translationKey: "admin.storage.dry_run", defaultText: "Dry run:" },
  yes: { translationKey: "admin.storage.yes", defaultText: "Yes" },
  no: { translationKey: "admin.storage.no", defaultText: "No" },
  account: { translationKey: "admin.storage.account", defaultText: "Account ID" },
  bytes: { translationKey: "admin.storage.bytes", defaultText: "Stored size" },
  files: { translationKey: "admin.storage.files", defaultText: "Files" },
  review: { translationKey: "admin.storage.review", defaultText: "Review high usage" },
  empty: { translationKey: "admin.storage.empty", defaultText: "No confirmed chat files on this page." },
  refresh: { translationKey: "admin.storage.refresh", defaultText: "Refresh" },
  inspect: { translationKey: "admin.storage.inspect", defaultText: "Check storage inventory" },
  inspecting: { translationKey: "admin.storage.inspecting", defaultText: "Checking inventory…" },
  inspectFailed: { translationKey: "admin.storage.inspect_failed", defaultText: "The inventory check could not finish. Please try again later." },
  inspectSkipped: { translationKey: "admin.storage.inspect_skipped", defaultText: "Another storage check is already running. Refresh later." },
  inspectDone: { translationKey: "admin.storage.inspect_done", defaultText: "Inventory checked. No files were deleted." },
  previous: { translationKey: "admin.storage.previous", defaultText: "Previous" },
  next: { translationKey: "admin.storage.next", defaultText: "Next" },
} as const;
