import { createHmac, randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import { config } from "dotenv";
import { encode } from "next-auth/jwt";
import postgres from "postgres";

config({ path: ".env.local" });
config({ path: ".env", override: false });

test("new account can complete its profile through web and native", async ({ browser, request, baseURL }) => {
  const origin = process.env.PROFILE_TEST_ORIGIN ?? baseURL;
  const url = process.env.POSTGRES_POOLER_URL ?? process.env.POSTGRES_URL;
  const secret = process.env.AUTH_SECRET ?? process.env.NEXTAUTH_SECRET;
  if (!origin || !url || !secret) throw new Error("Profile test requires origin, database and auth configuration");
  const sql = postgres(url, { max: 1, prepare: false });
  const ids = [randomUUID(), randomUUID()];
  const context = await browser.newContext();
  try {
    for (const id of ids) {
      await sql`insert into "User" (id,email) values (${id},${`profile-${id.slice(0,8)}@example.invalid`})`;
    }
    const payload = Buffer.from(JSON.stringify({ sub: ids[0], exp: Date.now() + 120_000 })).toString("base64url");
    const token = `${payload}.${createHmac("sha256", secret).update(payload).digest("base64url")}`;
    const headers = { Authorization: `Bearer ${token}` };
    const data = { firstName: "Signup", lastName: "Test", dateOfBirth: "1986-07-16" };
    const start = Date.now();
    const response = await request.patch(`${origin}/api/mobile/profile`, { headers, data });
    expect(response.status()).toBe(200);
    const saved = await response.json();
    expect(saved.user.dateOfBirth).toBe(data.dateOfBirth);
    expect(saved.user.firstName).toBe(data.firstName);
    console.log(`Native profile request: ${Date.now() - start} ms`);
    const repeated = await request.patch(`${origin}/api/mobile/profile`, { headers, data });
    expect(repeated.status()).toBe(200);
    const blocked = await request.patch(`${origin}/api/mobile/profile`, { headers, data: { ...data, dateOfBirth: "1987-01-01" } });
    expect(blocked.status()).toBe(409);
    const session = await request.get(`${origin}/api/mobile/auth/session`, { headers });
    expect((await session.json()).session.user.dateOfBirth).toBe(data.dateOfBirth);
    const malformed = await request.patch(`${origin}/api/mobile/profile`, { headers: { ...headers, "Content-Type": "application/json" }, data: "{" });
    expect(malformed.status()).toBe(400);
    const cookieName = origin.startsWith("https:") ? "__Secure-authjs.session-token" : "authjs.session-token";
    const webSession = {
      id: ids[1], sub: ids[1], email: `profile-${ids[1].slice(0,8)}@example.invalid`,
      role: "regular", firstName: null, lastName: null, dateOfBirth: null,
      imageVersion: null, allowPersonalKnowledge: false, dbRefreshedAt: Date.now(),
    };
    const webToken = await encode({ secret, salt: cookieName, token: webSession });
    await context.addCookies([{ name: cookieName, value: webToken, url: origin, httpOnly: true, secure: origin.startsWith("https:"), sameSite: "Lax" }]);
    const page = await context.newPage();
    await page.goto(`${origin}/complete-profile`);
    await page.locator('#firstName').fill("Signup");
    await page.locator('#lastName').fill("Test");
    await page.locator('#dob').fill(data.dateOfBirth);
    await page.locator('button[type="submit"]').click();
    await expect(page).not.toHaveURL(/\/complete-profile/, { timeout: 20_000 });
    const [stored] = await sql`select "dateOfBirth", "firstName", "lastName" from "User" where id=${ids[1]}`;
    expect(stored.firstName).toBe("Signup");
    expect(stored.lastName).toBe("Test");
    expect(stored.dateOfBirth).toBeTruthy();
    console.log("PASS: web onboarding saved and navigated; native save, retry, DOB lock, session refresh, malformed JSON");
  } finally {
    await context.close();
    try {
      // Remove only the audit events generated by these temporary test users.
      await sql`delete from "AuditLog" where "actorId" in ${sql(ids)}`;
      await sql`delete from "User" where id in ${sql(ids)}`;
    } finally {
      await sql.end();
    }
  }
});
