export const REFERRAL_COPY = {
  title: "Creator referrals",
  view_link: "View link",
  link_details: "Referral details",
  link_details_description: "Terms and performance for this referral link. The summary boxes above the table include all your links and coupons.",
  short_expiry: "Expiry",
  short_duration: "Duration",
  per_user: "Per user",
  short_months: "{count} months",
  short_days: "{count} days",
  short_first: "First recharge",
  users_first_recharge: "User's first recharge",
  short_indefinite: "Indefinite",
  short_cutoff: "Until cutoff",
  link_options: "Referral options",
  balance_chart: "Earnings and payouts",
  dashboard_title: "Share links and track your earnings",
  coupons_unavailable: "Coupon information could not be confirmed. Reload this page to retry.",
  dashboard_description: "View your assigned referral links, commission terms, coupon activity, and payouts.",
  creator_description: "Share your assigned links and track commissions on the full amount paid. Commission expiry is based on each referred user's signup unless a fixed cutoff is shown.",
  assigned: "Assigned on",
  link: "Referral link",
  expiry: "Commission expiry",
  expiry_at: "{date} IST",
  months_display: "{count} months after each user's signup",
  days_display: "{count} days after each user's signup",
  cutoff_display: "Every eligible recharge before the fixed cutoff",
  until_first_recharge: "After each user's first successful recharge",
  no_expiry: "No expiry",
  expired: "Expired",
  program_paused: "Program not enabled",
  program_note: "Your assigned links are shown here. New referral signups and commissions are currently not enabled by the admin.",
  share: "Share link",
  sharing: "Sharing...",
  copying: "Copying...",
  share_message: "Join KhasiGPT using my referral link.",
  share_unavailable: "Sharing failed. Please try again or copy the link.",
  copy_unavailable: "Could not copy the link. Please try again.",
  description: "Creators earn commission on the full amount paid. Referral links do not discount the user's recharge.",
  loading: "Loading referrals...",
  unavailable: "Referral information could not be confirmed. Please retry.",
  retry: "Retry",
  save: "Save",
  saving: "Saving...",
  saved: "Saved successfully.",
  create: "Assign referral link",
  creator: "Creator",
  select_creator: "Select creator",
  inventory: "Referral inventory",
  inventory_description: "Track referral links, signup attribution, recharge commissions, and creator payouts.",
  add_new: "Add new referral",
  settings: "Referral and coupon settings",
  code: "Code",
  validity: "Validity",
  reward: "Commission earned",
  payouts: "Payouts",
  payout_status: "Payout status",
  recharges: "Eligible recharges",
  revenue: "Eligible recharge volume",
  status: "Status",
  actions: "Actions",
  active: "Active",
  inactive: "Inactive",
  make_inactive: "Make inactive",
  make_active: "Make active",
  details: "View details",
  no_activity: "No activity yet",
  delete: "Delete",
  deleting: "Deleting...",
  delete_title: "Delete this unused entry?",
  delete_description: "This permanently deletes the unused link or coupon. Entries with signups, payments, or payouts must be made inactive instead to keep their history.",
  delete_in_use: "This entry has signup or payment history. Make it inactive instead.",
  cancel: "Cancel",
  close: "Close",
  copied: "Copied successfully.",
  no_payouts: "No creator payouts recorded yet.",
  coupon_summary: "Coupon summary",
  coupon_inventory: "Coupon inventory",
  coupon_inventory_description: "Track usage, availability, and recent redemptions.",
  add_coupon: "Add new coupon",
  edit_coupon: "Edit coupon",
  copy_code: "Copy coupon code",
  coupon_code_label: "Coupon code",
  creator_performance: "Creator performance",
  creator_performance_description: "Compare coupon redemptions, revenue, and creator rewards.",
  discount: "Discount %",
  valid_from: "Valid from",
  valid_until: "Valid until",
  creator_reward: "Creator reward %",
  coupon_description: "Description",
  coupon_description_placeholder: "Optional details shown in dashboards",
  save_changes: "Save changes",
  create_coupon: "Create coupon",
  creating: "Creating...",
  no_creator_activity: "No creator activity recorded yet.",
  redemptions: "Redemptions",
  coupon_revenue: "Revenue",
  operations: "Options for {code}",
  percentage: "Creator commission (%)",
  commission_percentage: "Commission %",
  earnings_unavailable: "Earnings totals could not be confirmed. Reload this page to retry.",
  duration: "Commission duration",
  indefinite: "Every recharge indefinitely",
  months: "Every recharge for a number of months after signup",
  first_recharge: "First successful recharge only",
  signup_window: "Every recharge within a signup window or before a cutoff",
  month_count: "Number of months after signup",
  window_days: "Days after signup",
  cutoff: "Or an exact recharge cutoff (local time)",
  rule_note: "Each link keeps its assigned rules. Create a new link to change the terms. Pausing a link stops new signups and future commissions.",
  referral_access: "Referral access",
  coupon_access: "Coupon rewards and user discounts",
  enabled: "Enabled for everyone",
  admin_only: "Admins only",
  disabled: "Disabled",
  pause: "Pause",
  activate: "Activate",
  copy: "Copy referral link",
  signups: "Referred signups",
  earned: "Earned",
  paid: "Paid",
  remaining: "Unpaid balance",
  payout: "Record payment to creator",
  payout_note: "Record an amount you have already paid to the creator. This does not transfer money.",
  amount: "Amount paid (in currency units)",
  currency: "Currency",
  note: "Payment reference or note",
  reverse: "Reverse commission for refunded recharge",
  reversed: "Reversed",
  recent: "Recent recharge commissions",
  empty: "No referral links assigned yet.",
  previous: "Previous",
  next: "Next",
  join: "Join KhasiGPT",
  signup: "Sign up on the web",
  install: "Install Android app",
  welcome: "Create an account through this creator's link to join KhasiGPT.",
  percentage_display: "Creator commission: {percentage}%",
  signups_display: "Referred signups: {count}",
  rule_values: "{value}",
  link_display: "{link}",
  balance_display: "{currency} — Earned: {earned} · Paid: {paid} · Unpaid: {remaining}",
  coupon_note: "Creator codes do not change the price shown by Google Play. An eligible creator earns a commission from the purchase.",
  coupon_code: "Creator code (optional)",
} as const;
