export const REFERRAL_COPY = {
  title: "Creator referrals",
  description: "Creators earn commission on the full amount paid. Referral links do not discount the user's recharge.",
  loading: "Loading referrals...",
  unavailable: "Referral information could not be confirmed. Please retry.",
  retry: "Retry",
  save: "Save",
  saving: "Saving...",
  saved: "Saved successfully.",
  create: "Assign referral link",
  creator: "Creator",
  percentage: "Creator commission (%)",
  duration: "Commission duration",
  indefinite: "Every recharge indefinitely",
  months: "Every recharge for a number of months after signup",
  first_recharge: "First successful recharge only",
  signup_window: "Every recharge within a signup window or before a cutoff",
  month_count: "Number of months after signup",
  window_days: "Days after signup",
  cutoff: "Or an exact recharge cutoff (local time)",
  rule_note: "Each link keeps its assigned rules. Create a new link to change the terms. Pausing a link stops new signups and future commissions.",
  referral_access: "Referral access",
  coupon_access: "Coupon rewards and user discounts",
  enabled: "Enabled for everyone",
  admin_only: "Admins only",
  disabled: "Disabled",
  pause: "Pause",
  activate: "Activate",
  copy: "Copy referral link",
  signups: "Referred signups",
  earned: "Earned",
  paid: "Paid",
  remaining: "Unpaid balance",
  payout: "Record payment to creator",
  payout_note: "Record an amount you have already paid to the creator. This does not transfer money.",
  amount: "Amount paid (in currency units)",
  currency: "Currency",
  note: "Payment reference or note",
  reverse: "Reverse commission for refunded recharge",
  reversed: "Reversed",
  recent: "Recent recharge commissions",
  empty: "No referral links assigned yet.",
  previous: "Previous",
  next: "Next",
  join: "Join KhasiGPT",
  signup: "Sign up on the web",
  install: "Install Android app",
  welcome: "Create an account through this creator's link to join KhasiGPT.",
  percentage_display: "Creator commission: {percentage}%",
  signups_display: "Referred signups: {count}",
  rule_values: "{value}",
  link_display: "{link}",
  balance_display: "{currency} — Earned: {earned} · Paid: {paid} · Unpaid: {remaining}",
  coupon_note: "Creator codes do not change the price shown by Google Play. An eligible creator earns a commission from the purchase.",
  coupon_code: "Creator code (optional)",
} as const;
